# Generated by Django 3.2.5 on 2021-07-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20210704_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='name',
        ),
    ]
