# Generated by Django 3.2.5 on 2021-07-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_rename_title_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_run_fruit_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_run_gun_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_run_plant_model',
            field=models.BooleanField(default=False),
        ),
    ]
